[versions]
# Versions
androidMinSdkVersion = "21"
androidTargetSdkVersion = "33"
androidCompileSdkVersion = "33"

autoMinSdkVersion = "23"
autoTargetSdkVersion = "33"
autoCompileSdkVersion = "33"

composeMinSdkVersion = "23"
composeTargetSdkVersion = "33"
composeCompileSdkVersion = "33"

exampleMinSdkVersion = "23"
exampleTargetSdkVersion = "33"
exampleCompileSdkVersion = "33"
exampleNdkVersion = "23.2.8568313"

# Plugins
pluginJacoco = "0.2"
pluginGradle = "7.4.2"
pluginLicense = "0.9.0"
pluginMapboxAccessToken = "0.4.0"
pluginMapboxSdkRegistry = "1.2.2"
pluginMapboxSdkVersions = "1.1.3"
pluginPitest = "0.2.8"
pluginTaskTree = "2.1.0"
pluginPlayPublisher = "3.7.0"
pluginGradleVersions = "0.42.0"
pluginBinaryCompatibilityValidator = "0.8.0"

dokka = "1.7.20"
kotlin = "1.7.20"
detekt = "1.22.0"

# Dependencies

mapboxBase = "0.8.0"
mapboxGlNative = "11.0.0-beta.5"
mapboxCommon = "24.0.0-beta.5"
mapboxGestures = "0.8.0"
mapboxJavaServices = "5.4.1"

androidXTestMonitor = "1.6.1"
androidxActivityCompose = "1.4.0"
androidxAnnotation = "1.1.0"
androidxAppcompat = "1.6.1"
androidxArchCoreTest = "2.1.0"
androidxConstraintLayout = "2.0.0"
androidxCore = "1.9.0" # last version compatible with kotlin 1.8.10
androidxEspresso = "3.5.1"
androidxFragmentTesting = "1.5.0"
# can not bump to v1.6.0, due to incompatible
# `@androidx.annotation.VisibleForTesting(otherwise = null)`
# generated by the telemetry module setup, we can update either by updating the annotation
# processor in mapbox-android-base, or remove the module setup in mapbox-maps-android
androidxInterpolator = "1.0.0"
androidxJUnit = "1.1.5"
androidxLifecycle = "2.3.0"
androidxMultidex = "2.0.1"
androidxRecyclerView = "1.1.0"
androidxTest = "1.5.0"
androidxTestOrchestrator = "1.4.2"
androidxTestRunner = "1.5.2"
androidxUiAutomator = "2.2.0"

squareRetrofit = "2.9.0"
squareLeakCanary = "2.9.1"
materialDesign = "1.2.0"
googlePlayServicesLocation = "18.0.0"
googleCarAppLibrary = "1.2.0"
androidAutoMapboxMapSdk = "10.5.0"

# Use kotlinCoroutines to 1.6.1 to be compatible with platform runtime.
kotlinCoroutines = "1.6.1"
junit = "4.13.2"
mockk = "1.13.5"
robolectric = "4.9.2"
robolectricEgl = "gl1.1-android-2.1_r1"
lint = "30.4.2"
hamcrest = "2.1"
equalsVerifier = "3.14"
asyncInflater = "1.0.0"

compose = "1.3.2"
composeBom = "2023.01.00"
gradleVersionsPlugin = "0.42.0"
ksp = "1.0.8"
kotlinDataCompat = "0.7.0"

toster = "0.3.2"


[libraries]
plugin-gradle = { module = "com.android.tools.build:gradle", version.ref = "pluginGradle" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-jacoco = { module = "com.hiya:jacoco-android", version.ref = "pluginJacoco" }
plugin-license = { module = "com.jaredsburrows:gradle-license-plugin", version.ref = "pluginLicense" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

plugin-mapbox-accessToken = { module = "com.mapbox.gradle.plugins:access-token", version.ref = "pluginMapboxAccessToken" }
plugin-mapbox-sdkRegistry = { module = "com.mapbox.gradle.plugins:sdk-registry", version.ref = "pluginMapboxSdkRegistry" }
plugin-mapbox-sdkVersions = { module = "com.mapbox.mapboxsdk:mapbox-android-sdk-versions", version.ref = "pluginMapboxSdkVersions" }

plugin-pitest = { module = "pl.droidsonroids.gradle:gradle-pitest-plugin", version.ref = "pluginPitest" }
plugin-playPublisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "pluginPlayPublisher" }
plugin-gradleVersions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "pluginGradleVersions" }

# Dependencies

android-autoMapboxMapSdk = { module = "com.mapbox.maps:android", version.ref = "androidAutoMapboxMapSdk" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-archCoreTest = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCoreTest" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-fragmentTest = { module = "androidx.fragment:fragment-testing", version.ref = "androidxFragmentTesting" }
androidx-interpolators = { module = "androidx.interpolator:interpolator", version.ref = "androidxInterpolator" }
androidx-jUnitTestRules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx-lifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycleRuntimeTesting = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidxMultidex" }
androidx-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTestOrchestrator" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerView" }
androidx-testCore = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-testJUnit = { module = "androidx.test.ext:junit", version.ref = "androidxJUnit" }
androidx-testMonitor = { module = "androidx.test:monitor", version.ref = "androidXTestMonitor" }
androidx-testRunner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-uiAutomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxUiAutomator" }
asyncInflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version.ref = "asyncInflater" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material = { module = "androidx.compose.material:material" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4" }
compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
googleCarAppLibrary = { module = "androidx.car.app:app", version.ref = "googleCarAppLibrary" }
googleMaterialDesign = { module = "com.google.android.material:material", version.ref = "materialDesign" }
googlePlayServicesLocation = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayServicesLocation" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinDataCompatAnnotation = { module = "com.github.tobrun.kotlin-data-compat:annotation", version.ref = "kotlinDataCompat" }
kotlinDataCompatProcessor = { module = "com.github.tobrun.kotlin-data-compat:processor", version.ref = "kotlinDataCompat" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lintApi = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lintChecks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lintTests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

mapbox-annotations = { module = "com.mapbox.base:annotations", version.ref = "mapboxBase" }
mapbox-annotationsProcessor = { module = "com.mapbox.base:annotations-processor", version.ref = "mapboxBase" }
mapbox-base = { module = "com.mapbox.base:common", version.ref = "mapboxBase" }
mapbox-coreCommon = { module = "com.mapbox.common:common", version.ref = "mapboxCommon" }
mapbox-gestures = { module = "com.mapbox.mapboxsdk:mapbox-android-gestures", version.ref = "mapboxGestures" }
mapbox-glNativeSnapshot = { module = "com.mapbox.maps:android-core-internal", version.ref = "mapboxGlNative" }
mapbox-glNative = { module = "com.mapbox.maps:android-core", version.ref = "mapboxGlNative" }
mapbox-javaGeoJSON = { module = "com.mapbox.mapboxsdk:mapbox-sdk-geojson", version.ref = "mapboxJavaServices" }
mapbox-javaTurf = { module = "com.mapbox.mapboxsdk:mapbox-sdk-turf", version.ref = "mapboxJavaServices" }
mapbox-services = { module = "com.mapbox.mapboxsdk:mapbox-sdk-services", version.ref = "mapboxJavaServices" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockkAgentApi = { module = "io.mockk:mockk-agent-api", version.ref = "mockk" }
mockkAgentJvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
robolectricEgl = { module = "org.khronos:opengl-api", version.ref = "robolectricEgl" }

squareLeakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareLeakCanary" }
squareRetrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareRetrofit" }
squareRetrofitGsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "squareRetrofit" }

testUtils = { module = "com.android.tools:testutils", version.ref = "lint" }
toster = { module = "by.epicbot:toster", version.ref = "toster" }

[bundles]
base-dependencies = [ "mapbox-base", "kotlin", "androidx-appCompat", "androidx-coreKtx", "androidx-annotations"]
base-dependenciesTests = ["junit", "mockk", "androidx-testCore", "equalsVerifier", "robolectric"]
base-dependenciesAndroidTests = ["androidx-testRunner", "androidx-jUnitTestRules", "androidx-espresso"]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
taskTreeId = { id = "com.dorongold.task-tree", version.ref = "pluginTaskTree" }
binaryCompatibilityValidatorId = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "pluginBinaryCompatibilityValidator" }
